"""Initial migration

Revision ID: 0fee2125f69c
Revises: 
Create Date: 2026-06-24 15:57:47.852798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fee2125f69c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint('uq_habit_title', 'habits', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_habit_title', 'habits', type_='unique')
    op.alter_column('habits', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
